### ISSUE TITLE
Database v1

### ISSUE THREAD

**Issue by at-minhdao** [AT-PHPIntership/flappy-book#4]
![flappy_book_v3](https://user-images.githubusercontent.com/33854608/34474065-834a2d52-efac-11e7-875a-80d7ec0da2e1.png)

**Comment by at-nhuibo** [comment]
@at-minhdao 
- Bảng posts và books: nên có title/name: tên bài viết, sách; description: giới thiệu sơ lược; detail/content: mô tả chi tiết
- Bảng posts: cái column link á, ko biết dùng để làm gì
- Bảng books
 + nếu sách được tài trợ từ người nào đó thì sao??? phải log lại chứ nhỉ? nếu sau này có bảng xếp hạng ng tài trợ sách nhiều nhất thì làm sao... mình nghĩ nên có cột sponsor_id, có thể null, trỏ tới bảng users.
 + nếu người tài trợ sách thu hồi sách, hoặc sách bị mất thì sao? mình nghĩ nên có cột `status` nữa

**Comment by at-tuanphan** [comment]
- Mình nghĩ bảng `posts ` không cần columns `link` và `picture` vì  tất cả mình có thể dồn hết vào `content` được.
- Bảng `comments` nó sẽ có quan hệ theo kiểu `polymorphic` với các bảng khác, nên mình update lại tên cho trường `target_table` và `target_id` theo chuẩn `commentable_type` và `commentable_id` đúng hơn: https://laravel.com/docs/5.2/eloquent-relationships#polymorphic-relations
- Những trường có kiểu VARCHAR mọi người check lại và giới hạn lại số lượng, chứ như trường `employer_code` mà để 255 thì dư quá.

**Comment by at-nhannguyen2** [comment]
![flappy_book_v4](https://user-images.githubusercontent.com/33854583/34474382-9f74849c-efb0-11e7-8c8d-5c7439f799bc.png) 
em nối column from_person bảng books tới column employ_code bảng users không được,  
mong mấy anh giúp đỡ
